# Override file for development
version: '3.8'

services:
  parking-boss:
    environment:
      - NODE_ENV=development
    volumes:
      # Development: mount as read-write for easier debugging
      - ./db:/app/db
    ports:
      - "3000:3000"
    # Enable hot reload for development (if needed)
    # command: npm run dev